baseURL = 'https://rschmaelzle.github.io/'
languageCode = 'en-us'
title = 'Ralf Schmaelzle'
theme = 'PaperMod'

[params]
  defaultTheme = "light" 
  description = "Professor & Researcher"
  colorScheme = "avocado"
  
  [params.assets]
      disableHLJS = true # Optional
      customCSS = ["css/extended.css"]

[menu]
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv/"
    weight = 10

  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 20
	
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true